use std::sync::Arc;

use crate::client_protocol::project;
use crate::client_protocol::protocol::{
    ErrorCode, OperationKind, SessionBindingProjection, SessionInfo,
};
use crate::context_pipeline::{BudgetPolicy, CompactPolicy, manual_compact_eligible};
use crate::permission::PermissionSink;
use crate::runtime::spawn_turn;
use crate::session::store::Session;
use crate::types::LitecodeError;
use tokio_util::sync::CancellationToken;

use super::{SessionController, StartTurnError};

impl SessionController {
    /// Ensure a Projection exists for `session_id`. If not, delegate to
    /// `subscribe()` which creates a real Projection with a proper
    /// broadcast_rx and forwarding task.
    pub(super) async fn ensure_projection_for_turn(
        &mut self,
        session_id: &str,
    ) -> Result<(), StartTurnError> {
        if self.projections.contains_key(session_id) {
            return Ok(());
        }
        // Delegate to subscribe() which creates a real Projection.
        self.subscribe(session_id).await;
        if self.projections.contains_key(session_id) {
            Ok(())
        } else {
            Err(StartTurnError::Runtime(anyhow::anyhow!(
                "failed to subscribe to session {session_id}"
            )))
        }
    }

    pub async fn start_turn(
        &mut self,
        session_id: &str,
        input: &str,
        permission_sink: Arc<dyn PermissionSink>,
        turn_id: &str,
    ) -> Result<(), StartTurnError> {
        // Ensure the projection exists for this session.
        self.ensure_projection_for_turn(session_id).await?;

        // Ensure the SessionRecord exists.
        self.sessions
            .ensure_entry(session_id)
            .await
            .map_err(|e| StartTurnError::Runtime(anyhow::anyhow!("{e}")))?;

        // 2.14: the turn_id is generated by the caller (before the permission
        // sink is created) so the wire carries a real id end-to-end.
        let turn_id = turn_id.to_string();
        let sink = permission_sink;
        self.sessions
            .set_last_permission_sink(session_id, Arc::clone(&sink));
        self.runtime
            .reload_if_needed()
            .map_err(|e| StartTurnError::Runtime(anyhow::anyhow!("{e}")))?;

        let default_primary = self.runtime.desired_primary_agent();
        let primary_agent = self
            .sessions
            .resolve_primary_agent(session_id, default_primary, &self.runtime.resolved)
            .map_err(|e| StartTurnError::Runtime(anyhow::anyhow!("{e}")))?;

        let binding = self.session_binding(session_id);
        if let Some(proj) = self.projection_mut(session_id) {
            proj.context_window = binding.context_window;
        }

        // Reserve before spawning the runtime. This closes the old check/spawn/
        // register race with revert and standalone compaction.
        let step_max = self.runtime_step_max(session_id);
        self.sessions
            .reserve_turn(
                session_id,
                turn_id.clone(),
                step_max,
                &primary_agent,
                &self.project,
            )
            .map_err(|e| match e {
                crate::types::LitecodeError::AgentAlreadyRunning => {
                    StartTurnError::AgentAlreadyRunning
                }
                other => StartTurnError::Runtime(anyhow::anyhow!("{other}")),
            })?;

        // Spawn the turn using per-session primary + sticky model_id.
        let handle = match spawn_turn(
            &self.runtime,
            session_id.to_string(),
            self.sessions.clone(),
            input.to_string(),
            sink,
            turn_id.clone(),
        ) {
            Ok(handle) => handle,
            Err(error) => {
                self.sessions.release_turn_reservation(session_id, &turn_id);
                return Err(StartTurnError::Runtime(error));
            }
        };

        // Subscribe this connection to the per-session event broadcast.
        let _ = self.sessions.attach(session_id);

        let project = self.project.clone();
        if let Err(e) = self
            .sessions
            .start_turn(
                session_id,
                handle,
                &primary_agent,
                &project,
                self.sessions.clone(),
            )
            .await
        {
            self.sessions.release_turn_reservation(session_id, &turn_id);
            return Err(StartTurnError::Runtime(anyhow::anyhow!("{e}")));
        }

        let project_str = self.project.clone();
        let binding = self.session_binding(session_id);
        if let Some(proj) = self.projection_mut(session_id) {
            proj.turn_committed_start = proj.committed_end;
            proj.apply_turn_started(turn_id, step_max);
            proj.push_outgoing(project::session_snapshot(
                proj.snapshot(&project_str, &binding),
            ));
        }
        Ok(())
    }

    /// Start a one-shot manual compact operation. The returned id acknowledges
    /// that the exclusive lease and all immutable execution inputs were
    /// acquired; completion is delivered on the session event stream.
    pub async fn start_manual_compact(
        &mut self,
        session_id: &str,
    ) -> Result<String, LitecodeError> {
        self.subscribe_checked(session_id)
            .await
            .map_err(LitecodeError::Anyhow)?;
        self.sessions.ensure_entry(session_id).await?;
        self.runtime.reload_if_needed()?;

        let session_binding = self.session_binding(session_id);
        if session_binding.context_window == 0 {
            return Err(LitecodeError::Config(
                "no context window configured for this session".into(),
            ));
        }
        let compaction_binding = self.runtime.resolve_compaction_binding()?;
        let ctx = self.runtime.compaction_context();
        let compaction_system = self.runtime.compaction_system_prompt(&ctx);

        let lease = self.sessions.try_begin_operation(
            session_id,
            crate::session::manager::SessionOperationKind::Compact,
        )?;
        let operation_id = lease.operation_id().to_string();

        let mut transcript = self
            .sessions
            .with_entry_store(session_id, |s| Ok(s.load_transcript()?))
            .map_err(LitecodeError::Anyhow)?;
        Session::snip_stale_results(&mut transcript);
        let budget = BudgetPolicy::new(session_binding.context_window);
        let token_count = budget.token_count(&transcript, 0);
        if !manual_compact_eligible(session_binding.context_window, token_count) {
            return Err(LitecodeError::NothingToCompact);
        }
        if !CompactPolicy::can_compact(&budget, &transcript) {
            return Err(LitecodeError::NothingToCompact);
        }

        if let Some(proj) = self.projection_mut(session_id) {
            proj.context_window = session_binding.context_window;
            proj.context_tokens_estimate = token_count;
        }

        let sessions = Arc::clone(&self.sessions);
        let sid = session_id.to_string();
        let op_id = operation_id.clone();
        tokio::spawn(async move {
            let cancel = CancellationToken::new();
            let result = CompactPolicy::compact_now(
                &budget,
                &sessions,
                &sid,
                compaction_binding.provider.as_ref(),
                &compaction_binding.api_key,
                &compaction_binding.api_model_id,
                &compaction_system,
                compaction_binding.max_tokens,
                &mut transcript,
                &cancel,
                Some(&op_id),
            )
            .await
            .map(|_| ());

            if result.is_ok() {
                let _ = sessions.with_entry_store(&sid, |s| {
                    s.reload_persisted_max_seq()?;
                    Ok(())
                });
            }
            drop(lease);
        });

        Ok(operation_id)
    }

    pub async fn new_session(&mut self) -> anyhow::Result<String> {
        let agent_id = self.runtime.desired_primary_agent().to_string();
        let model_id = self
            .runtime
            .resolved
            .agents()
            .get(&agent_id)
            .map(|p| p.model_ref.as_str())
            .filter(|s| !s.is_empty());
        let sid = self
            .sessions
            .open_session(&self.project, &agent_id, model_id)
            .await
            .map_err(|e| anyhow::anyhow!("{e}"))?;

        let binding = self.session_binding(&sid);
        let project = self.project.clone();
        let buffer_len = self.sessions.entry_buffer_len(&sid);
        let snapshot = project::buffer_snapshot(
            &sid, &project, &binding, buffer_len, 0, buffer_len, None, None, None, 0, false,
        );
        self._workspace_outgoing.push(project::operation_result(
            OperationKind::NewSession,
            true,
            None,
            snapshot.clone(),
        ));
        self._workspace_outgoing
            .push(project::session_snapshot(snapshot));
        if let Ok(sessions) = self.list_sessions().await {
            let session_list_msg = project::session_list(sessions);
            for proj in self.projections.values_mut() {
                proj.push_outgoing(session_list_msg.clone());
            }
            self._workspace_outgoing.push(session_list_msg);
        }
        Ok(sid)
    }

    pub async fn delete_session(&mut self, id: &str) -> anyhow::Result<()> {
        // Atomically reserve the idle session; a turn or compact cannot start
        // between the product gate and the destructive delete.
        let _lease = self
            .sessions
            .try_begin_operation(id, crate::session::manager::SessionOperationKind::Delete)
            .map_err(|e| anyhow::anyhow!("{e}"))?;

        // SessionManager.remove_session handles cancel + SQLite delete + lifecycle.
        self.sessions
            .remove_session(id)
            .map_err(|e| anyhow::anyhow!("{e}"))?;
        self.projections.remove(id);

        // Workspace-level outs: delete must not depend on remaining projections
        // (Session List alone / deleting the only subscribed session).
        if let Ok(sessions) = self.list_sessions().await {
            self._workspace_outgoing
                .push(project::session_list(sessions));
        }
        let project_str = self.project.clone();
        let snapshot = project::buffer_snapshot(
            id,
            &project_str,
            &SessionBindingProjection::default(),
            0,
            0,
            0,
            None,
            None,
            None,
            0,
            false,
        );
        self._workspace_outgoing.push(project::operation_result(
            OperationKind::DeleteSession,
            true,
            None,
            snapshot,
        ));
        Ok(())
    }

    pub async fn list_sessions(&mut self) -> anyhow::Result<Vec<SessionInfo>> {
        let db_path = self.runtime.db_path();
        let sessions_mgr = self.sessions.clone();
        let db_sessions = Session::list_sessions(&db_path)?;
        let default_primary = self.runtime.desired_primary_agent();
        let mut result = Vec::with_capacity(db_sessions.len());
        for (id, project, updated_at, preview, _agent_id, _model_id) in db_sessions {
            if sessions_mgr.is_session_empty(&id).await {
                continue;
            }
            let running = sessions_mgr.is_turn_running(&id).await;
            let turn = if running {
                sessions_mgr
                    .get_cached_progress(&id)
                    .map(|p| project::turn_progress_to_snapshot(&p))
            } else {
                None
            };
            let binding = project::binding_projection(
                &sessions_mgr,
                &id,
                &self.runtime.resolved,
                default_primary,
            );
            result.push(SessionInfo {
                id: id.clone(),
                project,
                updated_at,
                preview,
                running,
                turn,
                agent_id: binding.agent_id,
                model_id: binding.model_id,
                api_model_id: binding.api_model_id,
                label: binding.label,
                parent_session_id: None,
                parent_call_id: None,
            });
        }
        Ok(result)
    }

    // ── per-session operations ──

    pub fn revert_to_user_anchor(&mut self, session_id: &str, k: u32) -> anyhow::Result<()> {
        let project = self.project.clone();
        let binding = self.session_binding(session_id);
        let Some(proj) = self.projection_mut(session_id) else {
            return Err(anyhow::anyhow!("no session bound"));
        };
        proj.revert_to_user_anchor(k, &project, &binding)
    }

    pub fn revert_files(&mut self, session_id: &str, k: u32) -> anyhow::Result<()> {
        let project = self.project.clone();
        let binding = self.session_binding(session_id);
        let workspace_root = self.project.clone();
        let snapshots_dir = self.runtime.workspace.paths.snapshots_dir.clone();
        let Some(proj) = self.projection_mut(session_id) else {
            return Err(anyhow::anyhow!("no session bound"));
        };
        proj.revert_files(k, &project, &binding, &workspace_root, &snapshots_dir)
    }

    pub fn set_active_primary(&mut self, session_id: &str, agent_id: &str) -> anyhow::Result<()> {
        let project = self.project.clone();
        if self.is_session_busy_for(session_id) {
            let binding = self.session_binding(session_id);
            if let Some(proj) = self.projection_mut(session_id) {
                proj.push_operation_error(
                    OperationKind::SetActivePrimary,
                    ErrorCode::AgentAlreadyRunning,
                    "agent already running".into(),
                    &project,
                    &binding,
                );
            }
            return Ok(());
        }
        self.runtime.reload_if_needed()?;
        match crate::runtime::RuntimeHandle::validate_primary_agent(
            &self.runtime.resolved,
            agent_id,
        ) {
            Ok(()) => {
                self.sessions
                    .set_agent_id(session_id, agent_id.to_string())
                    .map_err(|e| anyhow::anyhow!("{e}"))?;
                // Only agent_id — do not touch model_id (decoupled sticky).
                let binding = self.session_binding(session_id);
                if let Some(proj) = self.projection_mut(session_id) {
                    proj.context_window = binding.context_window;
                    proj.push_operation_ok(OperationKind::SetActivePrimary, &project, &binding);
                }
                Ok(())
            }
            Err(e) => {
                let binding = self.session_binding(session_id);
                if let Some(proj) = self.projection_mut(session_id) {
                    proj.push_operation_error(
                        OperationKind::SetActivePrimary,
                        ErrorCode::InvalidRequest,
                        e.to_string(),
                        &project,
                        &binding,
                    );
                }
                Ok(())
            }
        }
    }

    /// Persist sticky session `model_id` only (does not touch `agent_id`).
    pub fn set_session_model(&mut self, session_id: &str, model_id: &str) -> anyhow::Result<()> {
        let project = self.project.clone();
        if self.is_session_busy_for(session_id) {
            let binding = self.session_binding(session_id);
            if let Some(proj) = self.projection_mut(session_id) {
                proj.push_operation_error(
                    OperationKind::SetModel,
                    ErrorCode::AgentAlreadyRunning,
                    "agent already running".into(),
                    &project,
                    &binding,
                );
            }
            return Ok(());
        }
        self.runtime.reload_if_needed()?;
        if !self.runtime.resolved.global().models.contains_key(model_id) {
            let binding = self.session_binding(session_id);
            if let Some(proj) = self.projection_mut(session_id) {
                proj.push_operation_error(
                    OperationKind::SetModel,
                    ErrorCode::InvalidRequest,
                    format!("model '{model_id}' not found"),
                    &project,
                    &binding,
                );
            }
            return Ok(());
        }
        self.sessions
            .set_session_model_id(session_id, Some(model_id.to_string()))
            .map_err(|e| anyhow::anyhow!("{e}"))?;
        let binding = self.session_binding(session_id);
        if let Some(proj) = self.projection_mut(session_id) {
            proj.context_window = binding.context_window;
            proj.refresh_context_estimate();
            proj.push_operation_ok(OperationKind::SetModel, &project, &binding);
        }
        Ok(())
    }

    pub fn set_thinking_tier(&mut self, session_id: &str, tier: &str) -> anyhow::Result<()> {
        let project = self.project.clone();
        let parsed = crate::platform_knobs::ThinkingTier::parse(tier).ok_or_else(|| {
            anyhow::anyhow!("invalid thinking_tier '{tier}' (expected low|medium|high)")
        })?;
        if self.is_session_busy_for(session_id) {
            let binding = self.session_binding(session_id);
            if let Some(proj) = self.projection_mut(session_id) {
                proj.push_operation_error(
                    OperationKind::SetThinkingTier,
                    ErrorCode::AgentAlreadyRunning,
                    "agent already running".into(),
                    &project,
                    &binding,
                );
            }
            return Ok(());
        }
        self.sessions
            .set_thinking_tier(session_id, parsed)
            .map_err(|e| anyhow::anyhow!("{e}"))?;
        let binding = self.session_binding(session_id);
        if let Some(proj) = self.projection_mut(session_id) {
            proj.push_operation_ok(OperationKind::SetThinkingTier, &project, &binding);
        }
        Ok(())
    }

    pub fn set_context_mode(&mut self, session_id: &str, mode: &str) -> anyhow::Result<()> {
        let project = self.project.clone();
        let parsed = crate::platform_knobs::ContextMode::parse(mode).ok_or_else(|| {
            anyhow::anyhow!("invalid context_mode '{mode}' (expected standard|max)")
        })?;
        if self.is_session_busy_for(session_id) {
            let binding = self.session_binding(session_id);
            if let Some(proj) = self.projection_mut(session_id) {
                proj.push_operation_error(
                    OperationKind::SetContextMode,
                    ErrorCode::AgentAlreadyRunning,
                    "agent already running".into(),
                    &project,
                    &binding,
                );
            }
            return Ok(());
        }
        self.sessions
            .set_context_mode(session_id, parsed)
            .map_err(|e| anyhow::anyhow!("{e}"))?;
        let binding = self.session_binding(session_id);
        if let Some(proj) = self.projection_mut(session_id) {
            proj.context_window = binding.context_window;
            proj.refresh_context_estimate();
            proj.push_operation_ok(OperationKind::SetContextMode, &project, &binding);
        }
        Ok(())
    }

    pub fn materialize_range(
        &self,
        session_id: &str,
        start: usize,
        end: usize,
    ) -> anyhow::Result<super::MaterializedRange> {
        self.projection(session_id)
            .ok_or_else(|| anyhow::anyhow!("no session bound"))?
            .materialize_range(start, end)
    }
}
